<?php

namespace Pilotabai\CompetitionDbBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQueryBuilder($websiteFilter = null, $competitionValFilter = null, $specialityValFilter = null, $levelValFilter = null)
    {
        $qb = $this->createQueryBuilder('category');

        if ($websiteFilter) {
            $qb->andWhere('category.website LIKE :website')
                ->setParameter('website', '%'.$websiteFilter.'%');
        }

        if ($competitionValFilter) {
            $qb->andWhere('category.competitionValue LIKE :competitionValue')
                ->setParameter('competitionValue', '%'.$competitionValFilter.'%');
        }

        if ($specialityValFilter) {
            $qb->andWhere('category.specialityValue LIKE :specialityValue')
                ->setParameter('specialityValue', '%'.$specialityValFilter.'%');
        }

        if ($levelValFilter) {
            $qb->andWhere('category.levelValue LIKE :levelValue')
                ->setParameter('levelValue', '%'.$levelValFilter.'%');
        }

        return $qb;
    }
}
