<?php

namespace Pilotabai\CompetitionDbBundle\Repository;

use Pilotabai\CompetitionDbBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllQueryBuilder($categoryId = null, $phase = null)
    {
        $qb = $this
            ->_em->createQueryBuilder()->select('g')->from($this->_entityName, 'g')
            ->leftJoin('g.category', 'c')->addSelect('c');

        if ($categoryId) {
            $qb->andWhere('c.id LIKE :cat')
                ->setParameter('cat', '%'.$categoryId.'%');
        }

        if ($phase) {
            $qb->andWhere('g.phase LIKE :ph')
                ->setParameter('ph', '%'.$phase.'%');
        }

        return $qb;
    }
}
